name: 'Setup Node.js and pnpm'
description: 'Setup Node.js, pnpm, and install dependencies with caching'

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 'lts/*'
        # It seems this may be required for OIDC to work properly, because it pulls in something
        # related to auth according to the documentation: https://github.com/actions/setup-node
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'

    - name: Update NPM to latest
      # This needs to be 11.5.1 or later for OIDC support
      shell: bash
      run: npm install -g npm@latest

    - name: Setup yarn classic and yarn berry
      shell: bash
      run: |
        corepack enable
        cd ~
        yarn set version classic
        cd $GITHUB_WORKSPACE

    - name: Install dependencies
      shell: bash
      run: pnpm install
