name: 'Package Build and Publish'
description: 'Build and publish a package to JSR and NPM'

inputs:
  package-name:
    description: 'Name of the package to build and publish'
    required: true
  npm-token:
    description: 'NPM token for authentication'
    required: true
  github-token:
    description: 'GitHub token for creating git tags'
    required: true
  skip-jsr:
    description: 'Skip JSR publishing'
    required: false
    default: 'false'
  skip-npm:
    description: 'Skip NPM publishing'
    required: false
    default: 'false'
  create-release:
    description: 'Create GitHub release after tagging'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Build dependencies and ${{ inputs.package-name }}
      shell: bash
      run: pnpm --filter ${{ inputs.package-name }}... build

    - name: Publish ${{ inputs.package-name }} to JSR
      if: inputs.skip-jsr != 'true'
      shell: bash
      run: pnpm --filter ${{ inputs.package-name }} jsr:publish

    - name: Add Auth Token for npm
      if: inputs.skip-npm != 'true'
      shell: bash
      run: echo "//registry.npmjs.org/:_authToken=${{ inputs.npm-token }}" > ~/.npmrc

    - name: Publish ${{ inputs.package-name }} to NPM
      if: inputs.skip-npm != 'true'
      shell: bash
      working-directory: packages/${{ inputs.package-name }}
      run: pnpm npm:publish

    - name: Create and push git tag for ${{ inputs.package-name }}
      shell: bash
      working-directory: packages/${{ inputs.package-name }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        # Configure git to use the GitHub token for authentication
        git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

        # Get the package version from package.json
        PACKAGE_VERSION=$(node -p "require('./package.json').version")

        # Get the actual package name from package.json and remove scope if present
        PACKAGE_NAME=$(node -p "require('./package.json').name.replace(/^@[\\w-]+\//, '')")

        # Create the git tag in the format: {package-name}-v{version}
        GIT_TAG="${PACKAGE_NAME}-v${PACKAGE_VERSION}"

        echo "Creating git tag: $GIT_TAG"

        # Create the tag locally
        git tag "$GIT_TAG"

        # Push the tag to origin
        git push origin "$GIT_TAG"

        echo "Successfully created and pushed git tag: $GIT_TAG"

        # Export variables for the next step
        echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
        echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
        echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV
        echo "RELEASE_NAME=${PACKAGE_NAME} v${PACKAGE_VERSION}" >> $GITHUB_ENV

    - name: Create GitHub Release for ${{ inputs.package-name }}
      if: inputs.create-release == 'true'
      shell: bash
      working-directory: packages/${{ inputs.package-name }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        echo "Creating GitHub release for $RELEASE_NAME with tag $GIT_TAG"

        # Check if release already exists
        if gh release view "$GIT_TAG" &>/dev/null; then
          echo "Release already exists for tag $GIT_TAG, skipping creation"
          exit 0
        fi

        # Extract changelog content
        CHANGELOG_FILE="changelog-content.txt"
        if npx tsx ../../scripts/extractChangelogForRelease.ts "$PACKAGE_NAME" "$PACKAGE_VERSION" --quiet > "$CHANGELOG_FILE" 2>&1; then
          echo "✅ Successfully extracted changelog content"
          CHANGELOG_CONTENT=$(cat "$CHANGELOG_FILE")
        else
          echo "⚠️  Failed to extract changelog content, using fallback message"
          CHANGELOG_CONTENT="Release notes for $PACKAGE_VERSION - See CHANGELOG.md for details."
        fi

        # Create the release using GitHub CLI
        if ! gh release create "$GIT_TAG" \
          --title "$RELEASE_NAME" \
          --notes "$CHANGELOG_CONTENT" \
          --verify-tag; then
          echo "Failed to create release, but continuing..."
          exit 0
        fi

        echo "Successfully created release: $RELEASE_NAME"

        # Clean up changelog file if it exists
        [ -f "$CHANGELOG_FILE" ] && rm "$CHANGELOG_FILE"
